CSharpMVCDemo/Models/Demo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSharpMVCDemo.Models
{
    public class Demo
    {
        public double no1 { get; set; }
        public double no2 { get; set; }

        public double tot { get; set; }
    }

}

CSharpMVCDemo/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CSharpMVCDemo.Models
{
    public class Student
    {
        [Required]
        [DataType(DataType.Text)]
        [DisplayName("StudentId")]
        public int StudentId { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [DisplayName("StudentName")]
        public string StudentName { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [DisplayName("Age")]
        public int Age { get; set; }
    }
}

CSharpMVCDemo/Controllers/DemoController.cs
using CSharpMVCDemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CSharpMVCDemo.Controllers
{
    public class DemoController : Controller
    {
        // GET: Demo
        public ActionResult Index()
        {
            return View(new Demo());
        }

        [HttpPost]

        public ActionResult Index(Demo c, string calc)
        {
            if(calc == "add")
            {
                c.tot = c.no1 + c.no2;
            }
            else if(calc == "min")
            {
                c.tot = c.no1 - c.no2;
            }
            else if (calc == "sub")
            {
                c.tot = c.no1 * c.no2;
            }
            else 
            {
                c.tot = c.no1 / c.no2;
            }
            return View(c);
        }
        
    }
}

CSharpMVCDemo/Controllers/ErrorHandlingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CSharpMVCDemo.Controllers
{
    public class ErrorHandlingController : Controller
    {
        // GET: ErrorHandling
        public ActionResult Index()
        {
            return View();
        }
        [HandleError]
        [HandleError(ExceptionType = typeof(DivideByZeroException), View = "Error1")]
        [HandleError(ExceptionType = typeof(ArgumentOutOfRangeException), View = "Error2")]
        public ActionResult Index1()
        {
            int a = 1;
            int b = 0;
            int c = 0;
            c = a / b; //it would cause exception.
            return View();
        }


        [HandleError(ExceptionType = typeof(DivideByZeroException), View = "Error1")]
        [HandleError(ExceptionType = typeof(ArgumentOutOfRangeException), View = "Error2")]
        [HandleError] // this will work, go to the default: view = "Error";
        public ActionResult Index2()
        {
            int a = 1;
            int b = 0;
            int c = 0;
            c = a / b; //it would cause exception.
            return View();
        }
    }
}

CSharpMVCDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CSharpMVCDemo.Controllers
{
    
    public class HomeController : Controller
    {
        [HandleError]
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CSharpMVCDemo/Controllers/StudentController.cs
using CSharpMVCDemo.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics.SymbolStore;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace CSharpMVCDemo.Controllers
{
    public class StudentController : Controller
    {
        static IList<Student> studentList = new List<Student>{
                new Student() { StudentId = 1, StudentName = "John", Age = 18 } ,
                new Student() { StudentId = 2, StudentName = "Steve",  Age = 21 } ,
                new Student() { StudentId = 3, StudentName = "Bill",  Age = 25 } ,
                new Student() { StudentId = 4, StudentName = "Ram" , Age = 20 } ,
                new Student() { StudentId = 5, StudentName = "Ron" , Age = 31 } ,
                new Student() { StudentId = 6, StudentName = "Chris" , Age = 17 } ,
                new Student() { StudentId = 7, StudentName = "Rob" , Age = 19 }
            };
        // GET: Student
        public ActionResult DisplayStudent()
        {

            return View(studentList.OrderBy(s => s.StudentId).ToList());

        }
        public ActionResult Index()
        {
            TempData["name"] = "Bang";
            ViewBag.TotalStudents = studentList.Count();

            ViewData["students"] = studentList;

            return View();
        }
        //Edit
        public ActionResult Edit(int Id)
        {
            //here, get the student from the database in the real application

            //getting a student from collection for demo purpose
            var std = studentList.Where(s => s.StudentId == Id).FirstOrDefault();

            return View(std);
        }
        [HttpPost]
        public ActionResult Edit(Student std)
        {
            if (ModelState.IsValid)
            { //checking model state

                //update student to db
                var student = studentList.Where(s => s.StudentId == std.StudentId).FirstOrDefault();
                studentList.Remove(student);
                studentList.Add(std);
                return RedirectToAction("DisplayStudent");
            }
            return View(std);

        }

        //Delete
        public ActionResult Delete(int Id)
        {
            var std = studentList.Where(s => s.StudentId == Id).FirstOrDefault();

            return View(std);
        }


        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(string Id)
        {
            int CurrentId = Int32.Parse(Id);
            var std = studentList.Where(s => s.StudentId == CurrentId).FirstOrDefault();
            studentList.Remove(std);
            return RedirectToAction("DisplayStudent");
        }

        //Create 
        public ActionResult Create()
        {
            return View(); 
        }
        [HttpPost]
        public ActionResult Create(Student std)
        {
            if (ModelState.IsValid)
            { //checking model state
                var st = studentList.OrderByDescending(s => s.StudentId).FirstOrDefault(); 
                //update student to db
                studentList.Add(std);
                std.StudentId = st.StudentId +1;
                return RedirectToAction("DisplayStudent");
            }
           
            return View(std);

        }

        public ActionResult Detail(int Id)
        {
            //getting a student from collection for demo purpose
            var std = studentList.Where(s => s.StudentId == Id).FirstOrDefault();

            return View(std);
        }
    }
}

CSharpMVCDemo/Views/Demo/Index.cshtml
@model CSharpMVCDemo.Models.Demo
@{
    ViewBag.Title = "May tinh";
}
<html>
<head>

</head>

<body>
    <h2>May tinh</h2>
    <div class=" row">
        @using (Html.BeginForm("/Index", "Demo", FormMethod.Post))
        {
            <div class="form-group">
                <label for="no1">No1</label>
                <input type="text" class="form-control" id="no1" name="no1" value="@Model.no1" />
            </div>
            <div class="form-group">
                <label for="no2">No2</label>
                <input type="text" class="form-control" id="no2" name="no2" value="@Model.no2" />
            </div>
            <div class="form-group">
                <label for="tot">Total</label>
                <input type="text" class="form-control" id="tot" name="tot" value="@Model.tot" />
            </div>

            <button type="submit" class="btn btn-info" id="add" value="add" name="calc">+</button>

            <button type="submit" class="btn btn-danger" id="min" value="min" name="calc">-</button>

            <button type="submit" class="btn btn-warning" id="sub" value="sub" name="calc">*</button>

            <button type="submit" class="btn btn-default" id="div" value="div" name="calc">/</button>
        }
    </div>
</body>
</html>

CSharpMVCDemo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CSharpMVCDemo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CSharpMVCDemo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CSharpMVCDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
    
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
   
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CSharpMVCDemo/Views/Student/Create.cshtml
@model CSharpMVCDemo.Models.Student

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CSharpMVCDemo/Views/Student/Delete.cshtml
@model CSharpMVCDemo.Models.Student

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "DisplayStudent")
        </div>
    }
</div>

CSharpMVCDemo/Views/Student/Detail.cshtml
@model CSharpMVCDemo.Models.Student

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.StudentId }) |
    @Html.ActionLink("Back to List", "DisplayStudent")
</p>

CSharpMVCDemo/Views/Student/DisplayStudent.cshtml
@model IEnumerable<CSharpMVCDemo.Models.Student>

@{
    ViewBag.Title = "DisplayStudent";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DisplayStudent</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StudentId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StudentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.StudentId }) |
                @Html.ActionLink("Details", "Detail", new { id = item.StudentId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.StudentId })
            </td>
        </tr>
    }

</table>

CSharpMVCDemo/Views/Student/Edit.cshtml
@model CSharpMVCDemo.Models.Student

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StudentId)

        <div class="form-group">
            @Html.LabelFor(model => model.StudentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CSharpMVCDemo/Views/Student/Index.cshtml
@using CSharpMVCDemo.Models;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<label>Total Students:</label>  @ViewBag.TotalStudents <br />
@TempData["name"]
<ul>
    @foreach (var std in ViewData["students"] as IList<Student>)
    {
        <li>
            @std.StudentName - @std.Age
        </li>
    }
</ul>